api_search実装
atsuki-uenishi/movicolle pull request #10
Opened 2022-05-07 04:14 UTC by atsuki-uenishi

APi利用しての検索の実装、投稿画面のデザインの変更しました。

2022-05-07 04:15 UTC, atsuki-uenishi commented
https://user-images.githubusercontent.com/49146986/167237790-6f0f0794-c0e8-4ede-9807-f9ed6e316d0b.mov

2022-05-07 06:08 UTC, Akihiro-Tnk requested changes
一度確認お願いします～

2022-05-07 06:08 UTC, Akihiro-Tnk commented on lib/controller/tmdb_api_controller.dart
> +const _posterUrl = 'http://image.tmdb.org/t/p/w300/';
変数の前にアンダーバーをつけるのはprivateな変数に対してのみですー！
複数クラスで使ってるので、これはアンダーバーをなくしたほうがいいかもですね

2022-05-07 06:08 UTC, Akihiro-Tnk commented on lib/screens/post_screen.dart
>    String? _posterUrl;
この命名は避けましょう～
他ファイルで同じ名前のグローバル変数を定義してますよね
他ファイルの変数はどこでも呼び出せる変数なので、もちろんこのクラス内でも呼び出せるはずです
その変数をこのクラス内で使うときに、どちらの変数か混乱してしまう可能性ありです

2022-05-07 06:08 UTC, Akihiro-Tnk commented on lib/screens/post_screen.dart
>    String? _posterUrl;
グローバル変数のほうを名前を変えることになると思いますので、こちらの名前は変えなくてよさそうですね

2022-05-07 06:08 UTC, Akihiro-Tnk commented on lib/screens/post_screen.dart
> +  Color switchColor(MaterialColor? color) {
いいアイデアがないですが、ここの処理もうちょっといい方法ありそうですね...
いったんOKです～

2022-05-07 06:08 UTC, Akihiro-Tnk commented on lib/screens/post_screen.dart
> +                      Icon(
ここは絶対for文を使いましょう
同じ処理は書かないようにするかんじでお願いしますー！
たとえば、星の数やアイコンが変わった場合に変更量が多くなっちゃいますー
```
for (int index = 0; index < _stars.length; index++)
  Icon(
    Icons.start,
    color: _rating >= index ? Colors.yellow : Colors.grey,
    size: 40.0,
  )
```

2022-05-09 03:47 UTC, Akihiro-Tnk approved these changes
OKです、マージしちゃってください〜

2022-05-09 06:12 UTC, merged