search_screen実装
atsuki-uenishi/movicolle pull request #11
Opened 2022-05-13 02:22 UTC by atsuki-uenishi

Firestoreのデータの編集、削除の実装とsearch_screenの実装をしました

2022-05-13 02:23 UTC, atsuki-uenishi commented
https://user-images.githubusercontent.com/49146986/168198755-8fc04208-7047-4464-bd91-2d561501bec5.mov

2022-05-13 02:23 UTC, atsuki-uenishi commented
https://user-images.githubusercontent.com/49146986/168198814-a0fda66c-3d78-4ce2-b4c1-08454eb1af1b.mov

2022-05-13 02:24 UTC, atsuki-uenishi commented
https://user-images.githubusercontent.com/49146986/168198999-a39fd66c-b5b6-4c79-a89d-24e3a00277b9.mov

2022-05-16 08:07 UTC, Akihiro-Tnk requested changes
１点だけ確認をお願いしますー！
最後の総仕上げにMVVMというアーキテクチャを意識してアプリを作りたいので、電話をしたいですー！

2022-05-16 08:07 UTC, Akihiro-Tnk commented on lib/screens/post_detail_screen.dart
> +    Navigator.pop(context);
32行目と38行目のNavigator.pop(context);はボタンのonPressed()でやりましょう
deletePostはあくまでポストを削除するための関数なので、popする役割はないですー！

2022-05-16 08:07 UTC, Akihiro-Tnk commented on lib/screens/post_detail_screen.dart
> +                    },
```
onPressed: () async {
  await deletePost();
  Navigator.pop(context);
}
```

2022-05-16 09:31 UTC, merged