googleログインの実装
atsuki-uenishi/movicolle pull request #4
Opened 2022-04-11 11:12 UTC by atsuki-uenishi

googleログインを実装しました。
初回ログイン時には、firestoreへ登録するようにしています。

2022-04-14 11:15 UTC, atsuki-uenishi commented
https://user-images.githubusercontent.com/49146986/163380222-0113ae3b-52cc-4321-af14-fb4b0caed2db.mov

2022-04-15 02:43 UTC, Akihiro-Tnk requested changes
いくつかコメントしたのでご確認お願いします！

2022-04-15 02:43 UTC, Akihiro-Tnk commented on lib/component/error_dialog.dart
> +      title: Text('エラー'),
text_data.dartに入れましょう〜

2022-04-15 02:43 UTC, Akihiro-Tnk commented on lib/component/error_dialog.dart
> +          child: Text('OK'),
text_data.dartに入れましょう〜

2022-04-15 02:43 UTC, Akihiro-Tnk commented on lib/screens/login_screen.dart
> +                      hintText: 'Password',
text_data.dartに入れましょう〜

2022-04-15 02:43 UTC, Akihiro-Tnk commented on lib/component/login_button.dart
> +import 'package:movicolle/main.dart';
ここでmain.dartをimportは不要かもです？？
クラス設計の観点で、main.dartをimportするのは極力避けたほうが良きです！

2022-04-15 02:43 UTC, Akihiro-Tnk commented on lib/component/login_button.dart
> +          //print(user);
基本的にネスト（インデント）は少ない方がキレイなコードとされています
なので、不要なelse文はない方が良きです
今回だと以下のような書き方ができますね

```
if (user != null) {
  Navigator.pushNamed(context, HomeScreen.id);
  return;
}
showDialog<void>(
  context: context,
  builder: (_) {
    return ErrorDialog();
  },
);
```

2022-04-15 02:43 UTC, Akihiro-Tnk commented on lib/authentication.dart
> +    if (googleSignInAccount != null) {
ここも工夫をすればif文でネストしなくて済みそうですね
以下のように書けないでしょうか？？
```
if (googleSignInAccount == null){
  return null;
}
final GoogleSignInAuthentication googleSignInAuthentication = await ...;
// 以下省略
```

2022-04-15 07:36 UTC, Akihiro-Tnk commented on lib/authentication.dart
> +  Future signOut() async {
Future<void>

2022-04-15 07:39 UTC, Akihiro-Tnk approved these changes
OKです！

2022-04-16 05:49 UTC, merged