画像アップロード実装
atsuki-uenishi/movicolle pull request #7
Opened 2022-04-25 01:56 UTC by atsuki-uenishi

image_pickerで画像を取得し、FireStorageにアップロードして、FireStoreにローカルのパスとFireStorageのパスを保存しています。
画面遷移時に画像が消えてしまうのでそこらへんの修正を現在しています。

2022-04-25 01:57 UTC, atsuki-uenishi commented
<img width="1383" alt="スクリーンショット 2022-04-25 10 48 36" src="https://user-images.githubusercontent.com/49146986/165008363-4243bbdf-491c-4055-ba70-2753420feae3.png">
<img width="1383" alt="スクリーンショット 2022-04-25 10 48 27" src="https://user-images.githubusercontent.com/49146986/165008368-43967c6e-cdcf-4093-bdf6-21cbef8c9df8.png">

2022-04-25 01:58 UTC, atsuki-uenishi commented
Uploading FullSizeRender.MOV…

2022-04-25 02:01 UTC, atsuki-uenishi commented
https://user-images.githubusercontent.com/49146986/165008680-d629dfee-50e1-413c-a7f6-a45082de8831.MOV

2022-04-25 05:16 UTC, Akihiro-Tnk requested changes
テーマカラーの設定いいですね！
あとはクラスの役割を意識して実装できるとものすごくよくなりますー！
どこかで通話の時間を設けましょう〜

2022-04-25 05:16 UTC, Akihiro-Tnk commented on lib/providers/theme_color_provider.dart
> +  MaterialColor? primaryColor = Colors.blue;
ここnullableにしないといけないです？？
nullableは取り扱い注意なので、できるだけ避けたいです！
nullを許容することになるので、もしここの値がnullだと実行時エラーの原因となりますー！
もし?マークを消しても問題ないのなら、そのようにしてください〜

2022-04-25 05:16 UTC, Akihiro-Tnk commented on lib/providers/user_provider.dart
> +      name: docs.data()!['name'],
ここはnullだとエラーになっちゃうので、`final docs = xxx`の下あたりにnullチェックを入れましょう〜
以下のイメージですー！
```
final data = docs.data();
if(data == null){
  return;
}
final userModels = xxx;
```

2022-04-25 05:16 UTC, Akihiro-Tnk commented on lib/providers/user_provider.dart
> +  Future fetchUserData() async {
`Future<void>`にしましょう！
他のプログラマーがこのコードを見たときに、返り値があるかどうかを確認しないとどんな関数かわからなくなりますー！

2022-04-25 05:16 UTC, Akihiro-Tnk commented on lib/screens/setting_screen.dart
> +    final FirebaseStorage storage = FirebaseStorage.instance;
画面のクラスでサーバー処理するのは避けましょう！
クラスには役割があり、screenクラスは基本的に描画のみをする役割を持ちます
このレポジトリだとサーバー処理の役割はproviderにありそうですね！

2022-04-25 05:16 UTC, Akihiro-Tnk commented on lib/screens/setting_screen.dart
> +    CollectionReference users =
これも他クラスの役割ですね

2022-04-25 05:16 UTC, Akihiro-Tnk commented on lib/screens/setting_screen.dart
> +    if (imgPathLocal != null) {
これも他クラスの役割ですね

2022-04-25 05:16 UTC, Akihiro-Tnk commented on lib/screens/theme_color_screen.dart
> +import 'package:flutter/material.dart';
テーマカラーの設定いいですね！！
このコミュニティで初の試みです！
面接ですごくいいアピールポイントになると思います！

2022-04-27 14:14 UTC, atsuki-uenishi commented
クラス分けと試しにFutureBuilder実装してみました。

2022-04-27 14:21 UTC, atsuki-uenishi commented
https://user-images.githubusercontent.com/49146986/165540292-9579eb01-66bf-4662-ae66-ef8fad6c6a92.MOV

2022-04-27 14:35 UTC, Akihiro-Tnk approved these changes
okです！

2022-04-28 03:50 UTC, merged